/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import nightSky from '../models/sky.glb'
import { a } from '@react-spring/three'


const Sky = (props) => {
    const nightRef = useRef();
  const { nodes, materials } = useGLTF(nightSky)
  return (
    <a.group ref={nightRef} {...props}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Sky}
        scale={73}
      />
    </a.group>
  )
}


export default Sky;